name: Production Build Push to Dockerhub image

on:
  push:
    branches:
      - hotfix/ransom
    paths:
      - "spm_backend/**"
      - ".github/workflow/docker.yaml"
  pull_request:
    branches:
      - hotfix/ransom
    paths:
      - "spm_backend/**"
      - ".github/workflow/docker.yaml"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Checkout Repository
        uses: actions/checkout@v2
        # This step checks out your code repository, so you have access to your code.

      
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      -
        name: Build and push
        run: |
          cd spm_backend
          docker build -t radamel/spm-backend:latest -f ./Dockerfile .
          docker push radamel/spm-backend:latest