name: Run Frontend CD

on:
  push:
    branches:
      - hotfix/ransom
    paths:
      - "spm_frontend/**"
      - ".github/workflow/frontend-cd.yaml"
  pull_request:
    branches:
      - hotfix/ransom
    paths:
      - "spm_frontend/**"
      - ".github/workflow/frontend-cd.yaml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Trigger Frontend Workflow
        working-directory: spm_frontend
        run: |
          npm install
          npm run build
          aws s3 sync ./dist/ s3://spm-frontend-final --delete