name: Run Frontend CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Trigger Frontend Workflow
        if: contains(steps.file_changes.outputs.files , 'spm_frontend/')
        working-directory: spm_frontend
        run: |
          cd spm_frontend
          npm install
          npm run build
          aws s3 sync ./build/ s3://spm-frontend --delete
          
     

  
