name: Run Tests

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: db
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        working-directory: spm_backend
        run: |
          pip install -r requirements.txt

      - name: Set up MYSQL
        working-directory: spm_backend
        run: |
          python -c "import mysql.connector; conn = mysql.connector.connect(host='localhost', user='user', password='password', database='db'); conn.close();"

      - name: Test Connection To Database
        working-directory: spm_backend
        run: pytest test_database_connection.py

      - name: Lint Python Code
        working-directory: spm_backend
        run: flake8 test_backend.py
        run: flake8 tests/test_close_role_listing.py
        run: flake8 tests/test_create_role_listing.py
        run: flake8 tests/test_cronjob_close_role_listing.py
        run: flake8 tests/test_cronjob_open_role_listing.py
        run: flake8 tests/test_edit_role_listing.py
        run: flake8 tests/test_get_open_role_listings.py
        run: flake8 tests/test_hr_get_all_role_listings.py
        run: flake8 tests/test_role_application.py

      - name: Run Tests
        working-directory: spm_backend
        run: pytest --exitfirst
