name: Run Tests

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: db
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        working-directory: spm_backend
        run: |
          pip install -r requirements.txt

      - name: Create Test Database
        run: |
          mysql -h 127.0.0.1 -P 3306 -u root -ppassword -e 'CREATE DATABASE IF NOT EXISTS db;'

      - name: Run Tests
        working-directory: spm_backend
        run: |
          python test_backend.py
